### ISSUE TITLE
Get `KF5WalletConfig.cmake`

### ISSUE THREAD

**Issue by real-yfprojects** [Templar-von-Midgard/git-credential-kwallet#3]
When running
```
cmake -DCMAKE_BUILD_TYPE=Release ..
```
I get the following error:
```
-- The CXX compiler identification is GNU 9.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:12 (find_package):
  By not providing "FindKF5Wallet.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "KF5Wallet", but CMake did not find one.

  Could not find a package configuration file provided by "KF5Wallet"
  (requested version 5.18.0) with any of the following names:

    KF5WalletConfig.cmake
    kf5wallet-config.cmake

  Add the installation prefix of "KF5Wallet" to CMAKE_PREFIX_PATH or set
  "KF5Wallet_DIR" to a directory containing one of the above files.  If
  "KF5Wallet" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!
```

Where/How do I get the KF5Wallet package or its package configuration file?
I am using KDE Plasma on Ubuntu and have KWallet installed.

**Comment by live125** [comment]
hiç bir fikrim yok bende bunu cözmeye calışıyorum tam olarak ne istediğini bana yaz hangi siteyi

**Comment by real-yfprojects** [comment]
> hiç bir fikrim yok bende bunu cözmeye calışıyorum tam olarak ne istediğini bana yaz hangi siteyi

I don't understand that. But it seems odd.

**Comment by Templar-von-Midgard** [comment]
Hi @real-yfprojects !

Apologies for the somewhat late reply, do you have `libkf5wallet-dev` installed?

**Comment by real-yfprojects** [comment]
> Apologies for the somewhat late reply, do you have `libkf5wallet-dev` installed?

No, I hadn't. I now was able to install it. Thank you!

How can I uninstall it - just in case?

**Comment by Templar-von-Midgard** [comment]
> How can I uninstall it - just in case?

Just delete the installed files.
